package handlers
















































































}	})		"message":    "Avatar uploaded successfully",		"avatar_url": avatarURL,		"user_id":    userID,		"success":    true,	c.JSON(http.StatusOK, gin.H{	avatarURL := "/uploads/" + filename	// Return response with avatar URL	}		return		})			"message": "Failed to save avatar file",			"error":   "UPLOAD_FAILED",		c.JSON(http.StatusInternalServerError, gin.H{	if err := c.SaveUploadedFile(file, filepath); err != nil {	// Save file	filepath := uploadDir + "/" + filename	filename := uuid.New().String() + filepath.Ext(file.Filename)	uploadDir := "./uploads"	// Create uploads directory if it doesn't exist	}		return		})			"message": "only image files are allowed (jpeg, png, gif, webp)",			"error":   "INVALID_FILE_TYPE",		c.JSON(http.StatusBadRequest, gin.H{	if !allowedTypes[file.Header.Get("Content-Type")] {	}		"image/webp": true,		"image/gif":  true,		"image/png":  true,		"image/jpeg": true,	allowedTypes := map[string]bool{	// Validate file type	}		return		})			"message": "file size exceeds 5MB limit",			"error":   "FILE_TOO_LARGE",		c.JSON(http.StatusBadRequest, gin.H{	if file.Size > maxFileSize {	maxFileSize := int64(5 * 1024 * 1024)	// Validate file size (max 5MB)	}		return		})			"message": "avatar file is required",			"error":   "INVALID_INPUT",		c.JSON(http.StatusBadRequest, gin.H{	if err != nil {	file, err := c.FormFile("avatar")	// Get file from form	}		return		})			"message": "user_id is required",			"error":   "INVALID_INPUT",		c.JSON(http.StatusBadRequest, gin.H{	if userID == "" {	userID := c.PostForm("user_id")func uploadAvatar(c *gin.Context) {// uploadAvatar handles file uploads for player avatars)	"github.com/google/uuid"	"github.com/gin-gonic/gin"	"path/filepath"	"net/http"import (